export interface guiaSPDTO{
    registroANS:string
    numeroGuiaPrestador:string
    guiaPrincipal:string
    numeroCarteira:string
    atendimentoRN:string
    codigoPrestadorNaOperadora:string
    nomeContratadoSolicitante:string
    conselhoProfissional:string
    numeroConselhoProfissional:string
    uf:string
    cbos:string
    caraterAtendimento:string
    cnes:string
    tipoAtendimento:string
    indicacaoAcidente:string
    regimeAtendimento:string
    valorTotalGeral:string
}